Repository WecoAI/aideml, pull requests merged in 2025-07, with the labels that each got.

#65 Migration to OpenAI responses API
  aide/backend/__init__.py
  aide/backend/backend_openai.py
  aide/backend/utils.py
Labels: enhancement, models

#66 fix import aide example in readme
  README.md
Labels: documentation

#71 Resolve moderate package vulnerability CVE-2024-47081
  requirements.txt
Labels: dependencies
